### ISSUE TITLE
Error after compilation

### ISSUE THREAD

**Issue by Karasu-O-Matic** [torkel104/libstrangle#13]
I follow the steps on the readme file, installing i386 dependencies and compiling the script, but every time I try to run I get this error:

`symbol lookup error: /usr/local/lib/libstrangle/lib32/libstrangle.so: undefined symbol: dlsym`

Have looked on google but don't seem to find a solution, could shred any light on this please?

Oh, I'm running debian stretch amd64.

Thanks!

**Comment by torkel104** [comment]
Try the new version of the makefile. Run 'make clean' before the other make commands.

**Comment by Karasu-O-Matic** [comment]
The user stan from gamingonlinux.com recommended me to add "-ldl" at the end of LDFLAGS in the makefile at that seemed to solve the issue. Thanks for your prompt reply though.
