### ISSUE TITLE
witcher2 crash on start

### ISSUE THREAD

**Issue by sss123next** [torkel104/libstrangle#18]
```
(gdb) where
#0  0x00000000 in ?? ()
#1  0xf7f5d11e in glXSwapIntervalMESA () from /home/sss/install/git/libstrangle_(fpslimit)/build/libstrangle32.so
#2  0xf7e91b9d in X11_GL_SetSwapInterval () from /usr/lib32/libSDL2-2.0.so.0
#3  0xf7e85484 in SDL_GL_SetSwapInterval_REAL () from /usr/lib32/libSDL2-2.0.so.0
#4  0x200b782b in ?? ()
#5  0x2009103b in ?? ()
#6  0x20047c8d in ?? ()
#7  0x20093bfb in ?? ()
#8  0x20093d54 in ?? ()
#9  0x2012fb77 in ?? ()
#10 0xf791f44a in start_thread () from /lib32/libpthread.so.0
#11 0xf7852cbe in clone () from /lib32/libc.so.6

```

not very usaful info, but this is all what i can get

**Comment by torkel104** [comment]
I'm afraid I can't reproduce this error and I can't pin down the problem from your stack trace. Try the latest version anyway, I doubt it will help but doesn't hurt to try.

Also is this with the Steam or GOG version? Does strangle work with other games for you?

**Comment by sss123next** [comment]
same with latest commit.
this is gog version
library does work for some games (trine for example)
i can provide more info, which kind of info do you need ?

**Comment by torkel104** [comment]
Could you try this branch? https://github.com/torkel104/libstrangle/tree/test1

Which graphics card and driver do you use? Does it work with or without vsync?

**Comment by sss123next** [comment]
with code from test branch it does work fine with AND without vsync
