### ISSUE TITLE
GitLab migration

### ISSUE THREAD

**Issue by milaq** [torkel104/libstrangle#2]
Hey mate,

first of all: I really appreciate your work on libstrangle. It is the one and only nicely working solution to limit the FPS on bad implemented games.
Furthermore I fully agree with your statement about Micro$oft here.

Although, I am not able to find the libstrangle repository on GitLab.
Can you send me in the right direction?

**Comment by GermainZ** [comment]
https://gitlab.com/torkel104/libstrangle

**Comment by milaq** [comment]
Thanks
