### ISSUE TITLE
libgcc/libgcc_s

### ISSUE THREAD

**Issue by Clipper996** [torkel104/libstrangle#23]
With Ubuntu 17.04 I get the following error while attempting to use the "strangle" command "error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory"

It worked fine on Ubuntu 16.04.

**Comment by torkel104** [comment]
Have you tried the solutions mentioned here? https://askubuntu.com/questions/386281/error-while-loading-shared-libraries-libglu-so-1

**Comment by Clipper996** [comment]
Yes I did, but to no avail.

It doesn't seem to work on Linux Mint 18.2 BETA anymore either (it worked well with 18.1), the only difference is that on Mint it doesn't even want to make the file.

Perhaps an updated library of some sort is incompatible with libstrangle now?

**Comment by Clipper996** [comment]
Okay so today i installed a fresh copy of Mint 18.1 and libstrangle worked as expected; however after installing another copy and updating some libraries via native update manager, it didn't want to make the file, citing an incompatible libgcc and libgcc_s.

Judging by these results, I'm guessing an update makes libstrangle incompatible now.

**Comment by torkel104** [comment]
Are you saying it wouldn't even compile? Paste the entire output please.

**Comment by Clipper996** [comment]
mkdir -p build/
gcc -rdynamic -fPIC -shared -Wall -std=c99 -fvisibility=hidden -DHOOK_DLSYM -Wl,-z,relro,-z,now -m64 -o build/libstrangle64.so src/libstrangle.c src/glx.c src/real_dlsym.c src/egl.c -ldl -lrt
gcc -rdynamic -fPIC -shared -Wall -std=c99 -fvisibility=hidden -DHOOK_DLSYM -Wl,-z,relro,-z,now -m32 -o build/libstrangle32.so src/libstrangle.c src/glx.c src/real_dlsym.c src/egl.c -ldl -lrt
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
makefile:28: recipe for target 'build/libstrangle32.so' failed
make: *** [build/libstrangle32.so] Error 1

**Comment by torkel104** [comment]
Try installing the packages gcc-multilib and ia32-libs

**Comment by Clipper996** [comment]
That fixed it, thank you.

May i suggest that you add these two libraries as potential prerequisites on ubuntu in readme.

**Comment by torkel104** [comment]
Yes, of course.
