### ISSUE TITLE
Ship with a copy of the GPL3 license

### ISSUE THREAD

**Issue by pyamsoft** [torkel104/libstrangle#5]
It is my understanding that the terms of the GPL3 require one to distribute software with a copy of the license. While the project includes the license in the COPYING file, it does not ship it with an install.

Perhaps an additional line can be added in the makefile install target to copy over the license file as well.

**Comment by torkel104** [comment]
What's the conventional path for such files?

**Comment by pyamsoft** [comment]
To be honest I don't know. That being said, I don't believe you would offend anybody by shipping it at, for example, 

`/usr/share/doc/libstrangle/LICENSE`

To my understanding, the important part is that you ship a copy of the license, not necessarily that it is installed into the correct directory.

**Comment by torkel104** [comment]
All right, let's go with that. Thank you for your contributions!
